use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

pub const WAYLAND_FLAGS: &str = r#"# Generated by spotify-adwaita
--ozone-platform=wayland
--enable-features=UseOzonePlatform,VaapiVideoDecoder
--disable-gpu-vsync
--disable-telemetry
--disable-breakpad
--disable-component-update
--disable-domain-reliability
--disable-renderer-backgrounding=false
"#;

pub fn configure_flags(config_dir: &Path) -> Result<()> {
    if !config_dir.exists() {
        fs::create_dir_all(config_dir)
            .with_context(|| format!("Failed to create config directory at {:?}", config_dir))?;
    }

    let flags_path = config_dir.join("spotify-flags.conf");
    fs::write(&flags_path, WAYLAND_FLAGS)
        .with_context(|| format!("Failed to write flags to {:?}", flags_path))?;

    Ok(())
}

pub fn remove_flags(config_dir: &Path) -> Result<()> {
    let flags_path = config_dir.join("spotify-flags.conf");
    if flags_path.exists() {
        fs::remove_file(&flags_path)
            .with_context(|| format!("Failed to remove flags file at {:?}", flags_path))?;
    }
    Ok(())
}

pub fn get_flags(config_dir: &Path) -> Option<String> {
    let flags_path = config_dir.join("spotify-flags.conf");
    if flags_path.exists() {
        fs::read_to_string(&flags_path).ok()
    } else {
        None
    }
}
